<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FiveEData</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="../../Data/dnd5e2014/sources.json"
      LogicalName="FiveEData.Data.dnd5e2014.sources.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/abilities.json"
      LogicalName="FiveEData.Data.dnd5e2014.abilities.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/skills.json"
      LogicalName="FiveEData.Data.dnd5e2014.skills.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/languages.json"
      LogicalName="FiveEData.Data.dnd5e2014.languages.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/creature-sizes.json"
      LogicalName="FiveEData.Data.dnd5e2014.creature-sizes.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/conditions.json"
      LogicalName="FiveEData.Data.dnd5e2014.conditions.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/damage-types.json"
      LogicalName="FiveEData.Data.dnd5e2014.damage-types.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/senses.json"
      LogicalName="FiveEData.Data.dnd5e2014.senses.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/alignments.json"
      LogicalName="FiveEData.Data.dnd5e2014.alignments.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/races.json"
      LogicalName="FiveEData.Data.dnd5e2014.races.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/subraces.json"
      LogicalName="FiveEData.Data.dnd5e2014.subraces.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/classes.json"
      LogicalName="FiveEData.Data.dnd5e2014.classes.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/subclasses.json"
      LogicalName="FiveEData.Data.dnd5e2014.subclasses.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/fighting-styles.json"
      LogicalName="FiveEData.Data.dnd5e2014.fighting-styles.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/metamagic-options.json"
      LogicalName="FiveEData.Data.dnd5e2014.metamagic-options.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/magic-schools.json"
      LogicalName="FiveEData.Data.dnd5e2014.magic-schools.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/spells.json"
      LogicalName="FiveEData.Data.dnd5e2014.spells.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/battle-master-maneuvers.json"
      LogicalName="FiveEData.Data.dnd5e2014.battle-master-maneuvers.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/eldritch-invocations.json"
      LogicalName="FiveEData.Data.dnd5e2014.eldritch-invocations.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/elemental-disciplines.json"
      LogicalName="FiveEData.Data.dnd5e2014.elemental-disciplines.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/channel-divinity-options.json"
      LogicalName="FiveEData.Data.dnd5e2014.channel-divinity-options.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/spell-slot-progressions.json"
      LogicalName="FiveEData.Data.dnd5e2014.spell-slot-progressions.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/extra-attack-progressions.json"
      LogicalName="FiveEData.Data.dnd5e2014.extra-attack-progressions.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/backgrounds.json"
      LogicalName="FiveEData.Data.dnd5e2014.backgrounds.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/ammunition.json"
      LogicalName="FiveEData.Data.dnd5e2014.ammunition.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/weapons.json"
      LogicalName="FiveEData.Data.dnd5e2014.weapons.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/armor.json"
      LogicalName="FiveEData.Data.dnd5e2014.armor.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/armor-usage.json"
      LogicalName="FiveEData.Data.dnd5e2014.armor-usage.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/shields.json"
      LogicalName="FiveEData.Data.dnd5e2014.shields.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/adventuring-gear.json"
      LogicalName="FiveEData.Data.dnd5e2014.adventuring-gear.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/container-capacities.json"
      LogicalName="FiveEData.Data.dnd5e2014.container-capacities.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/tool-families.json"
      LogicalName="FiveEData.Data.dnd5e2014.tool-families.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/tools.json"
      LogicalName="FiveEData.Data.dnd5e2014.tools.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mounts.json"
      LogicalName="FiveEData.Data.dnd5e2014.mounts.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/vehicles.json"
      LogicalName="FiveEData.Data.dnd5e2014.vehicles.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mount-support.json"
      LogicalName="FiveEData.Data.dnd5e2014.mount-support.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mount-vehicle-rules.json"
      LogicalName="FiveEData.Data.dnd5e2014.mount-vehicle-rules.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/trade-goods.json"
      LogicalName="FiveEData.Data.dnd5e2014.trade-goods.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/lifestyles.json"
      LogicalName="FiveEData.Data.dnd5e2014.lifestyles.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/food-drink.json"
      LogicalName="FiveEData.Data.dnd5e2014.food-drink.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/lifestyle-hospitality-costs.json"
      LogicalName="FiveEData.Data.dnd5e2014.lifestyle-hospitality-costs.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mundane-services.json"
      LogicalName="FiveEData.Data.dnd5e2014.mundane-services.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/weapon-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.weapon-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/armor-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.armor-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/adventuring-gear-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.adventuring-gear-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/tool-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.tool-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/mount-vehicle-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.mount-vehicle-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/trade-good-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.trade-good-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/expense-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.expense-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/lifestyle-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.lifestyle-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/race-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.race-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/class-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.class-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules/background-rule.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.background-rule.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/combat-actions.json"
      LogicalName="FiveEData.Data.dnd5e2014.combat-actions.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/cover.json"
      LogicalName="FiveEData.Data.dnd5e2014.cover.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/travel-pace.json"
      LogicalName="FiveEData.Data.dnd5e2014.travel-pace.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rest-types.json"
      LogicalName="FiveEData.Data.dnd5e2014.rest-types.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/downtime-activities.json"
      LogicalName="FiveEData.Data.dnd5e2014.downtime-activities.json" />
  </ItemGroup>

</Project>
