<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FiveEData</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="../../Data/dnd5e2014/sources.json"
      LogicalName="FiveEData.Data.dnd5e2014.sources.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/ammunition.json"
      LogicalName="FiveEData.Data.dnd5e2014.ammunition.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/weapons.json"
      LogicalName="FiveEData.Data.dnd5e2014.weapons.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/armor.json"
      LogicalName="FiveEData.Data.dnd5e2014.armor.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/armor-usage.json"
      LogicalName="FiveEData.Data.dnd5e2014.armor-usage.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/shields.json"
      LogicalName="FiveEData.Data.dnd5e2014.shields.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/adventuring-gear.json"
      LogicalName="FiveEData.Data.dnd5e2014.adventuring-gear.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/container-capacities.json"
      LogicalName="FiveEData.Data.dnd5e2014.container-capacities.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/tool-families.json"
      LogicalName="FiveEData.Data.dnd5e2014.tool-families.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/tools.json"
      LogicalName="FiveEData.Data.dnd5e2014.tools.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mounts.json"
      LogicalName="FiveEData.Data.dnd5e2014.mounts.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/vehicles.json"
      LogicalName="FiveEData.Data.dnd5e2014.vehicles.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mount-support.json"
      LogicalName="FiveEData.Data.dnd5e2014.mount-support.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mount-vehicle-rules.json"
      LogicalName="FiveEData.Data.dnd5e2014.mount-vehicle-rules.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/trade-goods.json"
      LogicalName="FiveEData.Data.dnd5e2014.trade-goods.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/lifestyles.json"
      LogicalName="FiveEData.Data.dnd5e2014.lifestyles.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/food-drink.json"
      LogicalName="FiveEData.Data.dnd5e2014.food-drink.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/lifestyle-hospitality-costs.json"
      LogicalName="FiveEData.Data.dnd5e2014.lifestyle-hospitality-costs.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/mundane-services.json"
      LogicalName="FiveEData.Data.dnd5e2014.mundane-services.json" />
    <EmbeddedResource
      Include="../../Data/dnd5e2014/rules.json"
      LogicalName="FiveEData.Data.dnd5e2014.rules.json" />
  </ItemGroup>

</Project>
